# Generated by Django 3.1.7 on 2022-09-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontweb', '0002_auto_20220925_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpost',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftpost',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftpost',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftpost',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftpost',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftpost',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftpost',
            name='sitename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='draftpost',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
