# Generated by Django 3.1.7 on 2022-09-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontweb', '0003_auto_20220925_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpost',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
