# Generated by Django 3.1.7 on 2022-09-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontweb', '0004_auto_20220925_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('sitename', models.CharField(blank=True, max_length=255, null=True)),
                ('urlsource', models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
