# Generated by Django 4.1.1 on 2022-09-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontweb', '0005_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Companie',
        ),
    ]
