# Generated by Django 4.1.1 on 2022-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontweb', '0006_rename_company_companie'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpost',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
