# Generated by Django 4.1.1 on 2022-09-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontweb', '0007_draftpost_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companie',
            name='urlsource',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
