# Generated by Django 4.1.1 on 2022-09-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontweb', '0009_alter_companie_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpost',
            name='meta_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
